nacos:
  config:
    server-addr: nacos.lcrs.vip
    type: yaml
    auto-refresh: true
    data-id: quartz.yml
    remote-first: true
    namespace: a5a6c5e6-e712-4757-b192-911c1c5a2710
    bootstrap:
      enable: true

