server:
  port: 9010


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456


xxl:
  job:
    admin:
      addresses: https://127.0.0.1/xxl-job-admin
    accessToken:
    executor:
      appname: ali-executor
      address:
      port: 18001
      ip:
      logpath: /data/dynamic/log
      logretentiondays: 30
